import Head from 'next/head'
import Form from '../components/form/Form'
import styles from '../styles/Home.module.css'
import Text from '../components/text/Text'

export default function Home() {
  return (
    <div>
      
      <Head>
        <title>Log in</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Form/>
        <Text/>
      </main>

    </div>
  )
}
